; vim:ft=avra:shiftwidth=2:tabstop=2:expandtab:
#define CMD0        0
#define CMD0_ARG    0
#define CMD0_CRC    0x94

#define CMD8        8
#define CMD8_ARG    0x0000001AA
#define CMD8_CRC    0x86

#define CMD58       58
#define CMD58_ARG   0x00000000
#define CMD58_CRC   0x00

#define CMD55       55
#define CMD55_ARG   0x00000000
#define CMD55_CRC   0x00

#define ACMD41      41
#define ACMD41_ARG  0x40000000
#define ACMD41_CRC  0x00

#define CMD17                   17
#define CMD17_CRC               0x00
#define SD_MAX_READ_ATTEMPTS    1563

#define CMD18       18
#define CMD18_CRC   0x00

#define CMD12 12
#define CMD12_ARG 0x00
#define CMD12_CRC 0

#define SD_READY    0
